string thisPath = Directory.GetParent(System.Reflection.Assembly.GetExecutingAssembly().Location).FullName;
string code = File.ReadAllText(Path.Combine(thisPath, "YourTank.cs"));
HttpClient client = new HttpClient();
Console.WriteLine("Uploading...");
ulong id = (ulong)Random.Shared.NextInt64();
await client.PostAsync($"https://highscores.neonrogue.net/uploadmap/{TANKS_.GameRoot.EndPoint}", new StringContent($"{id:D21}{Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(code))}"));
Console.WriteLine("Done!");
Console.WriteLine("Press Enter to exit");
Task.Run(() => Enumerable.Range(0, 5).Reverse().ToList().ForEach(i => { Console.WriteLine($"Auto Exiting in {i}"); Thread.Sleep(1000); if (i == 0) { Environment.Exit(1); } }));
Console.ReadLine();